## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file shm.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_63 = Integer(63); _sage_const_2p5 = RealNumber('2.5'); _sage_const_4 = Integer(4); _sage_const_67 = Integer(67); _sage_const_38 = Integer(38); _sage_const_10 = Integer(10); _sage_const_33 = Integer(33); _sage_const_27 = Integer(27)## This file (shm.sagetex.sage) was *autogenerated* from shm.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('shm', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 k=var('k')
 m=var('m')
 t=var('t')
 x=function('x',t)
 
 assume(k>_sage_const_0 )
 assume(m>_sage_const_0 )
 
 de = diff(x,t,_sage_const_2 )+(k*x)/m
 z=desolve(de,dvar=x,ivar=t)
except:
 _st_.goboom(_sage_const_27 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(k*x/m))
except:
 _st_.goboom(_sage_const_33 )
try:
 _st_.inline(_sage_const_1 , latex(z))
except:
 _st_.goboom(_sage_const_38 )
_st_.blockbegin()
try:
 m=_sage_const_1 
 k=_sage_const_1 
 t=var('t')
 de = diff(x,t,_sage_const_2 )+k*x/m
 z2 = desolve(de,dvar=x,ivar=t,ics=[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ])
 pl1 = plot(z2,(t,_sage_const_0 ,_sage_const_10 ),color=('red'), figsize = (_sage_const_4 ,_sage_const_2p5 ),axes_labels=['$t$','$x$'], fontsize=_sage_const_7 )
 
 m=_sage_const_1 
 k=_sage_const_1 
 z3 = desolve(de,dvar=x,ivar=t,ics=[_sage_const_1 ,_sage_const_1 ,_sage_const_0 ])
 print z3
 pl2 = plot(z3,(t,_sage_const_0 ,_sage_const_10 ), color=('green'))
 
 m=_sage_const_1 
 k=_sage_const_1 
 z4 = desolve(de,dvar=x,ivar=t, ics=[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ])
 pl3 = plot(z4,(t,_sage_const_0 ,_sage_const_10 ),color=('yellow'))
 
 m=_sage_const_1 
 k=_sage_const_1 
 z5 = desolve(de,dvar=x,ivar=t, ics=[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ])
 pl4 = plot(z5,(t,_sage_const_0 ,_sage_const_10 ),color=('violet'))
except:
 _st_.goboom(_sage_const_63 )
_st_.blockend()
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=pl1+pl2+pl3+pl4)
except:
 _st_.goboom(_sage_const_67 )
_st_.endofdoc()
